#+title: Readme
* Meta-WM
This windows manager for Meta Scientific Linux base on DWM.

* Requirements

+ Alacritty (shell)
+ imlib2
+ xsetroot package (status2d uses this to add colors on vanilla dwmbar)
+ JetbrainsMono Nerd Font or any nerd font but dont forget to set it in config.def.h
+ Materiald design icon font - [link](https://github.com/Templarian/MaterialDesign-Font/blob/master/MaterialDesignIconsDesktop.ttf)
+ Make sure to setup your terminal's theme accordingly do chadwm's theme such as nord, onedark etc...

** Other requirements
- picom
- feh
- acpi
- rofi

* Install
** Manual
#+begin_src bash
git clone https://github.com/yanboyang713/meta-wm.git --depth 1  ~/.config/metawm
cd ~/.config/metawm/
sudo make install
#+end_src
** Meta Scientific Linux/Arch Linux
Add the following code snippet to your /etc/pacman.conf:

#+begin_src file
[meta-scientific]
SigLevel = Optional
Server = https://raw.github.com/yanboyang713/Meta-Scientific-repository/main/repo
#+end_src
Then, run *sudo pacman -Sy* to update repository.

After, run *sudo pacman -S meta-wm*

* Run Meta-WM

** With startx

#+begin_src bash
startx ~/.config/metawm/scripts/run.sh
#+end_src

** With sx

#+begin_src bash
sx sh ~/.config/metawm/scripts/run.sh
#+end_src

(Make an alias for this :v)

#+begin_src bash
alias metawm='startx ~/.config/metawm/scripts/run.sh'
#+end_src

** With Display Manager

+ Step 1: Create a desktop entry (make sure to change `user` with your user):
  #+begin_src bash
    sudo touch /usr/share/xsessions/meta-wm.desktop
  #+end_src

  #+begin_src file
[Desktop Entry]
Name=meta-wm
Comment=Meta WM for Meta Scientific Linux
Exec=/home/yourusername/.config/metawm/scripts/./run.sh
Type=Application
  #+end_src

* Recompile
+ You need to recompile dwm after every change you make to its source code.
#+begin_src bash
cd ~/.config/chadwm/chadwm
rm config.h
sudo make install
#+end_src

* Change themes

- Bar  : in bar.sh (line 9) and config.def.h (line 35)
- eww  : in eww.scss (line 1)
- rofi : in config.rasi (line 15)

* Patches
+ barpadding
+ bottomstack
+ cfacts
+ dragmfact
+ dragcfact (took from [[https://github.com/bakkeby/dwm-flexipatch][bakkeby's build]])
+ fibonacii
+ gaplessgrid
+ horizgrid
+ movestack
+ vanity gaps
+ colorful tags
+ statuspadding
+ status2d
+ underline tags
+ notitle
+ winicon
+ [[https://github.com/PhyTech-R0/dwm-phyOS/blob/master/patches/dwm-6.3-patches/dwm-preserveonrestart-6.3.diff][preserveonrestart]]. This patch doesnt let all windows mix up into tag 1 after restarting dwm.
